### ISSUE TITLE
mmol/l AND mg/dl

### ISSUE THREAD

**Issue by W-vdK** [glucometers-tech/glucometerutils#109]
Hi,

Loop V2.1 (174)
Omnipod
Freestyle Libre
XDrip4IO5
Iphone 11

XDrip and apple Health app use mmol/l, as is standard in The Netherlands. Loop imports (and shows) data in mmol/l, but in the configuration everything is in mg/dl. I read that this was an issue early 2020, but is it still at the moment...?
How can I change this?

Thnx!
Woody

**Comment by Flameeyes** [comment]
Hello.

I'm afraid I'm not sure what configuration you're talking about? If you mean that `glucometer dump` returns it in mg/dL instead of mmol/L — that is indeed the case, I couldn't find anyone to confirm with a mg/dL Libre reader whether `$uom?` returns a different value from mine (https://github.com/glucometers-tech/glucometer-protocols/issues/10).

But given the list of software and hardware you listed, I somehow wonder if you're talking about this project at all?

**Comment by W-vdK** [comment]
Hi Flameeyes,
If you look at de screenshots, you will see that Xdrip uses mmol/l, and Loop uses both mmol/l AND mg/dl. Which is a bit strange..? 
If this is the wrong Github project: I'm sorry ;-)
Please refer me to the right one...

![IMG_938C8377B850-1](https://user-images.githubusercontent.com/83719249/118973344-e0451980-b971-11eb-9fce-4b808441e59c.jpeg)
![IMG_1A7804AAA212-1](https://user-images.githubusercontent.com/83719249/118973359-e2a77380-b971-11eb-8ba4-1a75cd081278.jpeg)
![IMG_A2C6141EE469-1](https://user-images.githubusercontent.com/83719249/118973367-e3d8a080-b971-11eb-9d91-857b0d75a0f8.jpeg)

**Comment by Flameeyes** [comment]
I'm honestly not sure where to point you at — your screenshot appear to clearly be for a mobile phone app… this repository is about a Python command-line tool.

Check in the app if there's a support link?
